### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by jbrucker** [wisaTong/Saltwater#48]
In README, please clarify the installation instructions.

Should have a section named "Installation Instructions", rather than "Standard Command".
Inside that section:
* first list the required software.  sbt does not need to be exactly version 1.2.3. I used 1.2.6 and it seems to work.
* then list commands that user should enter.  In a bash shell or Mac Terminal, this won't work: `sbt clean | compile | test`.  The vertical bar mean to pipe output of one command into stdin of next command.

**Comment by wisaTong** [comment]
Fixed #44
